#ifndef BANJO_KAZOOIE_CORE2_CH_GAMESELECT_H
#define BANJO_KAZOOIE_CORE2_CH_GAMESELECT_H

#include "config.h"

typedef enum {
    GAME_SELECT_INITIALIZE = 1,
    GAME_SELECT_IDLE = 2,
    GAME_SELECT_STARTING = 3,
    GAME_SELECT_STARTING_SILLY = 4,
    GAME_SELECT_ERASE_CONFIRMATION = 5,
    GAME_SELECT_DONE = 6
#ifdef OPTIONS_MENU
    ,
    GAME_SELECT_OPTIONS_MENU = 7
#endif
} GameSelectState;

#endif
