#include "config.h"

#if defined(WARP_CAULDRON_MENU) || defined(DPAD_FUNCTIONALITY) || defined(DONT_HOLD_Z_TO_USE_MOVES)
#define REPLACE_DIALOG_STRINGS
#endif

#ifdef REPLACE_DIALOG_STRINGS
 #ifdef WARP_CAULDRON_MENU
u8 *DIALOG_0F79_UNKNOWN_0_0_ORIGINAL = "YOU'VE ACTIVATED A MAGIC CAULDRON! FIND ~TO CREATE A SHORT CUT!";
u8 *DIALOG_0F79_UNKNOWN_0_0_REPLACEMENT = "MORE ";
 #endif

 #if defined(DPAD_FUNCTIONALITY) || defined(DONT_HOLD_Z_TO_USE_MOVES)
u8 *DIALOG_0B49_TALON_TROT_LEARN_0_2_ORIGINAL = "HOLD Z, THEN PRESS THE LEFT C BUTTON~~ GO PRACTICE!";
u8 *DIALOG_0B4A_TALON_TROT_REFRESHER_0_0_ORIGINAL = "TACKLE STEEP SLOPES WITH THE TALON TROT. HOLD Z, THEN PRESS THE LEFT C BUTTON~~";
u8 *DIALOG_0D35_WONDERWING_LEARN_0_2_ORIGINAL = "SURE DOES! HOLD Z AND PRESS THE RIGHT C BUTTON~~ USE IT WISELY THOUGH, AS THIS MOVE REQUIRES GOLD FEATHERS AND YOU CAN ONLY CARRY 10 OF THEM!";
u8 *DIALOG_0D36_WONDERWING_REFRESHER_0_0_ORIGINAL = "MAKE YOURSELF INVULNERABLE WITH THE WONDERWING BY HOLDING Z AND PRESSING THE RIGHT C BUTTON~~";

  #if defined(OPTIONS_MENU) || !defined(DPAD_FUNCTIONALITY)
u8 *DIALOG_DPAD_FUNCTIONALITY_GENERAL_ORIGINAL_CHUNK_A = ". ";
  #endif
  #if defined(OPTIONS_MENU) || !defined(DONT_HOLD_Z_TO_USE_MOVES)
u8 *DIALOG_DONT_HOLD_Z_GENERAL_ORIGINAL_CHUNK_A = "CONTINUE TO HOLD Z WHILE MOVING KAZOOIE AROUND WITH THE CONTROL STICK.";
u8 *DIALOG_DONT_HOLD_Z_GENERAL_ORIGINAL_CHUNK_B = "KEEP Z HELD AND USE THE CONTROL STICK TO MOVE AROUND.";
  #endif
 #endif

 #ifdef DPAD_FUNCTIONALITY
u8 *DIALOG_0DF4_BOTTLES_CAMERA_CONTROL_LEARN_0_1_ORIGINAL = "HELLO AGAIN! LET'S START WITH THE CAMERA CONTROLS, THEY'RE ON THE YELLOW C BUTTONS.~";
u8 *DIALOG_0DF4_BOTTLES_CAMERA_CONTROL_LEARN_0_1_REPLACEMENT = " YOU CAN ALSO USE THE D-PAD FOR DIFFERENT CONTROLS IF YOU'D LIKE.";
u8 *DIALOG_0DF4_BOTTLES_CAMERA_CONTROL_LEARN_0_5_ORIGINAL = "NO...HOLD R TO KEEP THE CAMERA BEHIND YOUR FEATHERY BUTT! ~TRY IT OUT, I'LL SEE YOU AT THE NEXT MOLEHILL.";
u8 *DIALOG_0DF4_BOTTLES_CAMERA_CONTROL_LEARN_0_5_REPLACEMENT = "FINALLY, PRESS L TO ENTER THE FIRST PERSON VIEW. ";

u8 *DIALOG_0DF5_BOTTLES_CAMERA_CONTROL_REFRESHER_0_0_ORIGINAL = "YOU CAN MOVE THE CAMERA VIEW WITH THE YELLOW C BUTTONS~ TAP R TO MOVE THE CAMERA BEHIND YOU, AND HOLD R TO KEEP THE CAMERA THERE.~";
u8 *DIALOG_0DF5_BOTTLES_CAMERA_CONTROL_REFRESHER_0_0_REPLACEMENT_A = " OR THE D-PAD. ";
u8 *DIALOG_0DF5_BOTTLES_CAMERA_CONTROL_REFRESHER_0_0_REPLACEMENT_B = " PRESS L TO ENTER THE FIRST PERSON VIEW.";

u8 *DIALOG_0F7C_BOTTLES_REMOVE_PIECE_INSTRUCTIONS_0_0_ORIGINAL = "TO REMOVE PIECES THAT YOU HAVE ALREADY PUT DOWN, PRESS THE DOWN C BUTTON~BUT ONCE THE PICTURE IS COMPLETE, ALL THE PIECES ARE STUCK THERE PERMANENTLY!";

u8 *DIALOG_0E24_UNKNOWN_0_0_ORIGINAL = "USE THE CONTROL STICK TO MOVE BANJO'S HAND. PRESS A TO PICK UP AND PUT DOWN PIECES, B TO RETURN THEM TO THE SIDE OR THE LEFT AND RIGHT C BUTTONS ~TO ROTATE THEM.";
u8 *DIALOG_0E24_UNKNOWN_0_0_REPLACEMENT = "OR D-PAD ";

u8 *DIALOG_DPAD_FUNCTIONALITY_GENERAL_REPLACEMENT_A = " OR D-PAD. ";
 #endif

 #ifdef DONT_HOLD_Z_TO_USE_MOVES
u8 *DIALOG_0B49_TALON_TROT_LEARN_0_2_REPLACEMENT = "YOU CAN MOVE KAZOOIE AROUND WITH THE CONTROL STICK. PRESS Z OR B TO STOP RUNNING.";
u8 *DIALOG_0B4A_TALON_TROT_REFRESHER_0_0_REPLACEMENT = "MOVE KAZOOIE AROUND WITH THE CONTROL STICK. PRESS Z OR B TO EXIT THE MOVE.";
u8 *DIALOG_0D35_WONDERWING_LEARN_0_2_REPLACEMENT = "USE THE CONTROL STICK TO MOVE AROUND. PRESS Z OR B TO STOP THE WONDERWING.";
u8 *DIALOG_0D36_WONDERWING_REFRESHER_0_0_REPLACEMENT = "USE THE CONTROL STICK TO MOVE AROUND. PRESS Z OR B TO EXIT THE MOVE.";
 #endif
#endif
