#include "config.h"
#include "enums.h"
#include "../gc/zoombox.h"

#ifdef OPTIONS_MENU
// IDs must be in the same order as they are in enums.h, except for QOL_ID_NONE.
static const scrollingMenuZoomboxFormat optionsZoomboxData[] = {
 #ifdef NOTE_SAVING
    {QOL_ID_NOTE_SAVING,                            "NOTE SAVING: ",          "",                 ZOOMBOX_SPRITE_8_MUSIC_NOTE_1,
     "MUSIC NOTES BECOME A PERMANENT COLLECTIBLE. THEY WON'T RESPAWN WHEN YOU DIE OR LEAVE THE LEVEL."},
 #endif
 #ifdef JINJO_SAVING
    {QOL_ID_JINJO_SAVING,                           "JINJO SAVING: ",         "",                 ZOOMBOX_SPRITE_22_JINJO_BLUE,
     "JINJOS BECOME A PERMANENT COLLECTIBLE. THEY WON'T RESPAWN WHEN YOU DIE OR LEAVE THE LEVEL."},
 #endif
 #ifdef HEALTH_SYSTEM_REWORK
    {QOL_ID_HEALTH_SYSTEM_REWORK,                   "HEALTH SYSTEM",          "REWORK: ",         ZOOMBOX_SPRITE_2C_HONEYCOMB,
     "LETS YOU ADD A 9TH HONEYCOMB TO THE HEALTH BAR. ALSO CHANGES HOW DOUBLE HEALTH WORKS. INSTEAD OF GIVING THE PLAYER MAXIMUM HEALTH, IT SIMPLY DOUBLES YOUR CURRENT HEALTH TOTAL."},
 #endif
 #ifdef WARP_CAULDRON_MENU
    {QOL_ID_WARP_CAULDRON_MENU,                     "WARP CAULDRON",          "MENU: ",           ZOOMBOX_SPRITE_56_WARP_CAULDRON,
     "ADDS A MENU TO THE WARP CAULDRONS, LETTING YOU WARP TO ANY CAULDRON YOU WANT."},
 #endif
 #ifdef DPAD_FUNCTIONALITY
    {QOL_ID_DPAD_FUNCTIONALITY,                     "D-PAD FUNCTIONALITY: ",  "",                 ZOOMBOX_SPRITE_F_BOTTLES,
     "ADDS FUNCTIONALITY TO THE D-PAD. USE IT TO TRIGGER C BUTTON MOVES, CONTROL THE CAMERA, NAVIGATE MENUS, AND ROTATE JIGSAW PIECES IN THE BOTTLE'S BONUS MINIGAME."},
 #endif
 #ifdef CAMERA_IMPROVEMENTS
    {QOL_ID_CAMERA_IMPROVEMENTS,                    "CAMERA",                 "IMPROVEMENTS: ",   ZOOMBOX_SPRITE_4_BANJO_1,
     "MAKES SLIGHT ADJUSTMENT TO IMPROVE THE CAMERA. IT DOESN'T DRASTICALLY CHANGE ANGLES WHEN ROTATING AROUND LEVEL GEOMETRY."},
 #endif
 #if defined(BUG_AND_OVERSIGHT_FIXES) || defined(VANILLA_SPECIFIC_BUG_AND_OVERSIGHT_FIXES)
    {QOL_ID_BUG_AND_OVERSIGHT_FIXES,                "BUG FIXES: ",            "",                 ZOOMBOX_SPRITE_34_TERMITE,
     "FIXES MANY BUGS AND ISSUES THROUGHOUT THE GAME."},
 #endif
 #ifdef IGNORE_FRAMERATE_ALTERING_OBJECTS
    {QOL_ID_IGNORE_FRAMERATE_ALTERING_OBJECTS,      "CONSISTENT",             "FRAMERATE: ",      ZOOMBOX_SPRITE_47_MUMMUM,
     "CERTAIN MAPS AND CUTSCENES ALTER THE FRAMERATE. CHANGE IT SO THESE MAPS RUN AT THE SAME FPS AS THE REST OF THE GAME."},
 #endif
 #ifdef SKIPPABLE_CUTSCENES
    {QOL_ID_SKIPPABLE_CUTSCENES,                    "SKIPPABLE",              "CUTSCENES: ",      0x5E, // Some enum names in 'zoombox.h' are wrong. 0x5E are Klungo's sprites.
     "ALLOWS YOU TO SKIP MANY CUTSCENES IN THE GAME."},
 #endif
 #ifdef REIMPLEMENT_EXIT_TO_WITCHS_LAIR
    {QOL_ID_REIMPLEMENT_EXIT_TO_WITCHS_LAIR,        "EXIT TO WITCH'S LAIR: ", "",                 ZOOMBOX_SPRITE_5_GRUNTILDA_2,
     "REIMPLEMENTS EXIT TO WITCH'S LAIR OPTION IN THE PAUSE MENU. YOU CAN ONLY USE IT IF YOU'RE IN A LEVEL."},
 #endif
 #ifdef TOGGLEABLE_MOVES
    {QOL_ID_TOGGLEABLE_MOVES,                       "TOGGLEABLE MOVES: ",     "",                 ZOOMBOX_SPRITE_D_KAZOOIE_1,
     "WHEN YOU USE TALON TROT OR WONDERWING, YOU DON'T NEED TO HOLD Z TO KEEP USING THE MOVE. TO EXIT, YOU CAN PRESS Z OR B."},
 #endif
 #ifdef ONLY_B_BUTTON_SKIPS_DIALOG
    {QOL_ID_ONLY_B_BUTTON_SKIPS_DIALOG,             "ONLY B BUTTON",          "SKIPS DIALOG: ",   ZOOMBOX_SPRITE_4_BANJO_1,
     "INSTEAD OF HOLDING L, R, AND B TO SKIP DIALOG, YOU CAN JUST PRESS B."},
 #endif
 #ifdef UNLOCK_PLACE_ALL_PUZZLE_PIECES
    {QOL_ID_UNLOCK_PLACE_ALL_PUZZLE_PIECES,         "UNLOCK PLACE ALL",       "PUZZLE PIECES: ",  ZOOMBOX_SPRITE_6_JIGGY_1,
     "UNLOCK THE ABILITY TO PLACE ALL JIGGIES IN A PICTURE BEFORE BOTTLES TEACHES YOU."},
 #endif
 #ifdef SAND_CASTLE_PERMANENTLY_DRAINED
    {QOL_ID_SAND_CASTLE_PERMANENTLY_DRAINED,        "SANDCASTLE DRAINED",     "PERMANENTLY: ",    ZOOMBOX_SPRITE_38_LEAKY,
     "THE SANDCASTLE IN TREASURE TROVE COVE BECOMES PERMANENTLY DRAINED WHEN YOU COLLECT THE SANDCASTLE JIGGY."},
 #endif
 #ifdef CLUCKER_CUTSCENE_VOLATILE_FLAG
    {QOL_ID_CLUCKER_CUTSCENE_VOLATILE_FLAG,         "CLUCKER CUTSCENE",       "PLAYS ONCE: ",     ZOOMBOX_SPRITE_55_ADULT_EEYRIE,
     "THE CUTSCENE THAT PLAYS WHEN YOU DEFEAT A CLUCKER WILL ONLY PLAY ONCE PER PLAY SESSION, INSTEAD OF WHEN YOU EXIT A LEVEL."},
 #endif
 #if defined(SHORTER_CHEATS) || defined(EASIER_CHEATS) || defined(ENTER_MORE_THAN_3_BANNED_CHEATS)
    {QOL_ID_CHEAT_CODES_OVERHAUL,                   "SANDCASTLE CHEAT",       "CODES OVERHAUL: ", ZOOMBOX_SPRITE_59_BLACK_SNIPPET,
     "MADE IMPROVEMENTS TO HOW YOU INPUT CHEAT CODES IN THE SANDCASTLE IN TREASURE TROVE COVE."},
 #endif
 #ifdef ADDITIONAL_CHEATS
    {QOL_ID_ADDITIONAL_CHEATS,                      "ADDITIONAL CHEAT",       "CODES: ",          ZOOMBOX_SPRITE_5B_CHEATO,
     "ADDS MORE CHEATS TO USE IN THE SANDCASTLE IN TREASURE TROVE COVE."},
 #endif

    {QOL_ID_NONE,                                   "END OF LIST",            "",                 ZOOMBOX_SPRITE_4_BANJO_1,
     "YOU SHOULDN'T BE ABLE TO READ THIS!"}
};
#endif
